### ISSUE TITLE
[BUG] Client network socket disconnected before secure TLS connection was established

### ISSUE THREAD

**Issue by nicolas-raoul** [liberodark/ODrive#114]
**To Reproduce**
1. Open ODrive
2. Enter Google username/password
3. At the authorization step, accept
4. Page takes some time, then displays this error:

```
Error: Client network socket disconnected before secure TLS connection was established
    at TLSSocket.onConnectEnd (_tls_wrap.js:1086:19)
    at Object.onceWrapper (events.js:273:13)
    at TLSSocket.emit (events.js:187:15)
    at endReadableNT (_stream_readable.js:1092:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
```

I have two accounts. It worked well for account A, then failed two times for account B.

I have no firewall.

**Screenshots**
![Screenshot from 2019-06-19 18-47-03](https://user-images.githubusercontent.com/99590/59755303-a7eabb80-92c2-11e9-8d04-8cf713a0d06e.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 19.04
 - Version: 0.2.2

**Comment by liberodark** [comment]
Thanks for information need to see that

**Comment by odyssey4me** [comment]
I'm seeing the same. After retrying a few times it seems to get through.
