### ISSUE TITLE
[BUG] Unhandled rejection Unkown folder

### ISSUE THREAD

**Issue by liberodark** [liberodark/ODrive#125]
**Describe the bug**
Unhandled rejection Unkown folder: 
```
Error: Unkown folder: 
    at Sync.getParent (/home/pc/Documents/Github/ODrive/app/core/sync.js:853:13)
    at Sync.onLocalFileAdded (/home/pc/Documents/Github/ODrive/app/core/sync.js:462:28)
```

**To Reproduce**
Sync my test account

**Desktop (please complete the following information):**
 - OS: Manjaro
 - Version 0.3.0

**Comment by liberodark** [comment]
And block on first sync... but after restart is sync files and sub folders
