### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by fabienlege** [liberodark/ODrive#128]
**Describe the bug**
Unable to finish setup. allowing access to google drive file

**To Reproduce**
1. Download and install deb version (for ubuntu 18.04)
2. Start odrive and install process
3. Login to Google drive (login password work great)
4. When google drive ask if we want to allow access to odrive, click allow
5. Waiting a while
6. Error occur and odrive seam to be not allowed, error showing instead (in same window that login prompt)

Message showing :
```Error: Client network socket disconnected before secure TLS connection was established
    at TLSSocket.onConnectEnd (_tls_wrap.js:1086:19)
    at Object.onceWrapper (events.js:273:13)
    at TLSSocket.emit (events.js:187:15)
    at endReadableNT (_stream_readable.js:1092:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)```

**Expected behavior**
A working login prompt...

**Screenshots**
If applicable, add screenshots to help explain your problem.
![image](https://user-images.githubusercontent.com/2045814/62767389-d865ff00-ba94-11e9-983e-e4949def4e23.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04
 - Version 0.2.2

**Comment by andrecavalcantebr** [comment]
I have same problem.
Ubuntu 18.04.3 OS
Desktop: Budgie
ODriver version: 0.2.2

**Comment by chwba** [comment]
Same problem.
Debian 10
Desktop: Gnome
Odrive 0.2.2

**Comment by chwba** [comment]
It works if building it manually from cloned git-repo

**Comment by fabienlege** [comment]
I've tried the @chwba solution. It seam to work to connect GDrive. but, just on the next step (when you click to "synchronize" button, a new error occur : 

```Files list done!
Files list done!
Files list done!
Files list done!
Files list done!
syncing false
Updated syncing status
Updating tray icon, connected:  true syncing:  false
{ Error: Internal Error
    at Request._callback (/opt/OpenDrive/resources/app.asar/node_modules/google-auth-library/lib/transporters.js:85:15)
    at Request.self.callback (/opt/OpenDrive/resources/app.asar/node_modules/request/request.js:185:22)
    at Request.emit (events.js:182:13)
    at Request.<anonymous> (/opt/OpenDrive/resources/app.asar/node_modules/request/request.js:1161:10)
    at Request.emit (events.js:182:13)
    at IncomingMessage.<anonymous> (/opt/OpenDrive/resources/app.asar/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:273:13)
    at IncomingMessage.emit (events.js:187:15)
    at endReadableNT (_stream_readable.js:1092:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
  code: 500,
  errors:
   [ { domain: 'global',
       reason: 'internalError',
       message: 'Internal Error' } ] }
```

**Comment by odyssey4me** [comment]
Looks like a duplicate of https://github.com/liberodark/ODrive/issues/114 ?

**Comment by gangodosamba** [comment]
Just need to open google drive config and allow "insecure" apps to get permission and its done.
