### ISSUE TITLE
[BUG] Initial download after setup stalls after 100-200Mb

### ISSUE THREAD

**Issue by hhannine** [liberodark/ODrive#135]
**Describe the bug**
Getting files at the beginning of the initial download takes a long time. After this the download from the cloud will start but it stalls after only 100-200Mb of files downloaded, a small fraction of the whole drive. Once ODrive crashed after being stalled at some early point in the sync. Restarting ODrive or the whole machine and rertrying sync hasn't helped. Removing and re-adding the account hasn't helped.

**To Reproduce**
1. Install 0.3.0 from AUR or 0.2.2 snap on Manjaro KDE 18.1
2. Add Google account
3. Start sync

**Expected behavior**
Sync downloads all of the files in Google Drive.

**Desktop (please complete the following information):**
 - OS: Manjaro KDE 18.1, Kernel 5.2.14-1-MANJARO, KDE version 5.16.5
 - Version: both 0.3.0 in AUR and the 0.2.2 snap.

**Additional context**
Syncing the contents of the same Google account works on my RHEL7.[5 or 6] workstation using ODrive 0.2.2.

Thanks for creating this nice tool! It has been a real pleasure to use on the RHEL machine where it works.

**Comment by hhannine** [comment]
I got a ~100Mb further by deleting a file from the cloud that was the last item acted on when running ODrive from the command line. It did stall again to another place. Why is this machine having issues cloning the drive whereas the RHEL machine has no issue?

**Comment by hhannine** [comment]
The stallings seem to accompany errors like this:

> Unhandled rejection ENOENT: no such file or directory, rename '/home/henri/Google Drive/.try-axo4j.aux.tmp' -> '/home/henri/Google Drive/JYU/Pro Gradu/jaxodraw/axodraw sty/testing/build/try-axo4j.aux'
{ [Error: ENOENT: no such file or directory, rename '/home/henri/Google Drive/.try-axo4j.aux.tmp' -> '/home/henri/Google Drive/JYU/Pro Gradu/jaxodraw/axodraw sty/testing/build/try-axo4j.aux']
  errno: -2,
  code: 'ENOENT',
  syscall: 'rename',
  path: '/home/henri/Google Drive/.try-axo4j.aux.tmp',
  dest:
   '/home/henri/Google Drive/JYU/Pro Gradu/jaxodraw/axodraw sty/testing/build/try-axo4j.aux' }
ignoring events for path /home/henri/Google Drive/JYU/Pro Gradu/jaxodraw/axodraw sty/testing/build/try-axo4j.pdf
ignoring events for path /home/henri/Google Drive/JYU/Pro Gradu/jaxodraw/axodraw sty/testing/build/NLO_gamma2qqg2.synctex.gz
ignoring events for path /home/henri/Google Drive/JYU/Pro Gradu/jaxodraw/axodraw sty/testing/build/try-axo4j.synctex.gz
ignoring events for path /home/henri/Google Drive/JYU/Pro Gradu/jaxodraw/axodraw sty/testing/build/NLO_gamma2qqg2.log
Events [ 'change' ]
Emitting last event for /home/henri/Google Drive/JYU/Pro Gradu/jaxodraw/axodraw sty/build/try-axo4j.aux

**Comment by chudkins** [comment]
I am also seeing this issue.  I'm also on Manjaro (18.1.4), also on KDE.

> Operating System: Manjaro Linux 
> KDE Plasma Version: 5.17.4
> KDE Frameworks Version: 5.64.0
> Qt Version: 5.13.2
> Kernel Version: 5.4.2-1-MANJARO
> OS Type: 64-bit
> Processors: 16 × AMD Ryzen 7 2700X Eight-Core Processor
> Memory: 62.8 GiB of RAM

When starting, I get this sort of output (sanitized):

> [carl@kotoko ~]$ /opt/OpenDrive/odrive
> /opt/OpenDrive/resources/app.asar/public
> app started on port 16409
> remote change false false
> local change false false
> Updating account info
> Updating tray icon, connected:  true syncing:  false
> New file since launch: /home/carl/Cloud/Google/...
> ...
> New file since launch: /home/carl/Cloud/Google/folder/folder/file.xml
> Initial scan complete. Ready for changes
> Saving account to db
> Saved account!
> Events [ 'addDir' ]
> Emitting last important event for /home/carl/Cloud/Google/folder addDir
> local change true true
> Updated syncing status
> Updating tray icon, connected:  true syncing:  true
> local change false false
> Updated syncing status
> Updating tray icon, connected:  true syncing:  false
> Unhandled rejection Unkown folder: 
> Error: Unkown folder: 
>     at Sync.getParent (/opt/OpenDrive/resources/app.asar/app/core/sync.js:853:13)
>     at Sync.onLocalDirAdded (/opt/OpenDrive/resources/app.asar/app/core/sync.js:642:28)
>     at queue (/opt/OpenDrive/resources/app.asar/app/core/sync.js:1081:61)
>     at Sync.queue (/opt/OpenDrive/resources/app.asar/app/core/sync.js:1103:15)
>     at LocalWatcher.watcher.on.path (/opt/OpenDrive/resources/app.asar/app/core/sync.js:1081:44)
>     at LocalWatcher.emit (events.js:182:13)
>     at LocalWatcher.analyzeCache (/opt/OpenDrive/resources/app.asar/app/core/localwatcher.js:171:12)
>     at Timeout.cache.timer.setTimeout [as _onTimeout] (/opt/OpenDrive/resources/app.asar/app/core/localwatcher.js:152:41)
>     at ontimeout (timers.js:425:11)
>     at tryOnTimeout (timers.js:289:5)
> Events [ 'add' ]
> Emitting last important event for /home/carl/Cloud/Google/file.jpg add
> Events [ 'addDir' ]
> Emitting last important event for /home/carl/Cloud/Google/folder addDir
> Events [ 'add' ]
> ...

The "new" files are actually already present locally.  I can't tell which folder it's talking about there (also note, "unkown" should be spelled "unknown") so I can't easily investigate.  I do see some network activity after it starts up, but I'm not sure what it's doing.

I can say that odrive is not downloading any new files, and it is not uploading files that I change.
