### ISSUE TITLE
[BUG] cannot connect to google drive account

### ISSUE THREAD

**Issue by refee** [liberodark/ODrive#143]
**Describe the bug**
Cannot connect to google drive account.

**To Reproduce**
- Start Odrive in terminal
- click  ODrive Settings -> Account -> Connect.
 - the system produced errors listed below:

```
mkdir: cannot create directory '/run/user/0': Permission denied
/snap/odrive/76/opt/OpenDrive/resources/app.asar/public
shm_open() failed: Permission denied
app started on port 16409
Error: ENOENT, public/javascript/preload.js not found in /snap/odrive/76/opt/OpenDrive/resources/app.asar
    at createError (ELECTRON_ASAR.js:131:17)
    at Object.module.(anonymous function) [as open] (ELECTRON_ASAR.js:195:23)
    at ReadStream.open (internal/fs/streams.js:110:12)
    at new ReadStream (internal/fs/streams.js:99:10)
    at Object.createReadStream (fs.js:1706:10)
    at SendStream.stream (/snap/odrive/76/opt/OpenDrive/resources/app.asar/node_modules/send/index.js:797:19)
    at SendStream.send (/snap/odrive/76/opt/OpenDrive/resources/app.asar/node_modules/send/index.js:708:8)
    at onstat (/snap/odrive/76/opt/OpenDrive/resources/app.asar/node_modules/send/index.js:730:10)
    at process.nextTick (ELECTRON_ASAR.js:21:28)
    at process._tickCallback (internal/process/next_tick.js:61:11)
Error: ENOENT, public/javascript/jquery.min.js not found in /snap/odrive/76/opt/OpenDrive/resources/app.asar
    at createError (ELECTRON_ASAR.js:131:17)
    at Object.module.(anonymous function) [as open] (ELECTRON_ASAR.js:195:23)
    at ReadStream.open (internal/fs/streams.js:110:12)
    at new ReadStream (internal/fs/streams.js:99:10)
    at Object.createReadStream (fs.js:1706:10)
    at SendStream.stream (/snap/odrive/76/opt/OpenDrive/resources/app.asar/node_modules/send/index.js:797:19)
    at SendStream.send (/snap/odrive/76/opt/OpenDrive/resources/app.asar/node_modules/send/index.js:708:8)
    at onstat (/snap/odrive/76/opt/OpenDrive/resources/app.asar/node_modules/send/index.js:730:10)
    at process.nextTick (ELECTRON_ASAR.js:21:28)
    at process._tickCallback (internal/process/next_tick.js:61:11)

GET /javascript/tether.min.js 404 3.779 ms - 1075
GET /stylesheets/styles.css 404 3.259 ms - 1073
GET /javascript/frontend.js 404 2.793 ms - 1073
GET /javascript/settings.js 404 1.865 ms - 1073

Error: ENOENT, public/javascript/tether.min.js not found in /snap/odrive/76/opt/OpenDrive/resources/app.asar
    at createError (ELECTRON_ASAR.js:131:17)
    at Object.module.(anonymous function) [as open] (ELECTRON_ASAR.js:195:23)
    at ReadStream.open (internal/fs/streams.js:110:12)
    at new ReadStream (internal/fs/streams.js:99:10)
    at Object.createReadStream (fs.js:1706:10)
    at SendStream.stream (/snap/odrive/76/opt/OpenDrive/resources/app.asar/node_modules/send/index.js:797:19)
    at SendStream.send (/snap/odrive/76/opt/OpenDrive/resources/app.asar/node_modules/send/index.js:708:8)
    at onstat (/snap/odrive/76/opt/OpenDrive/resources/app.asar/node_modules/send/index.js:730:10)
    at process.nextTick (ELECTRON_ASAR.js:21:28)
    at process._tickCallback (internal/process/next_tick.js:61:11)
Error: ENOENT, public/stylesheets/styles.css not found in /snap/odrive/76/opt/OpenDrive/resources/app.asar
    at createError (ELECTRON_ASAR.js:131:17)
    at Object.module.(anonymous function) [as open] (ELECTRON_ASAR.js:195:23)
    at ReadStream.open (internal/fs/streams.js:110:12)
    at new ReadStream (internal/fs/streams.js:99:10)
    at Object.createReadStream (fs.js:1706:10)
    at SendStream.stream (/snap/odrive/76/opt/OpenDrive/resources/app.asar/node_modules/send/index.js:797:19)
    at SendStream.send (/snap/odrive/76/opt/OpenDrive/resources/app.asar/node_modules/send/index.js:708:8)
    at onstat (/snap/odrive/76/opt/OpenDrive/resources/app.asar/node_modules/send/index.js:730:10)
    at process.nextTick (ELECTRON_ASAR.js:21:28)
    at process._tickCallback (internal/process/next_tick.js:61:11)
Error: ENOENT, public/javascript/frontend.js not found in /snap/odrive/76/opt/OpenDrive/resources/app.asar
    at createError (ELECTRON_ASAR.js:131:17)
    at Object.module.(anonymous function) [as open] (ELECTRON_ASAR.js:195:23)
    at ReadStream.open (internal/fs/streams.js:110:12)
    at new ReadStream (internal/fs/streams.js:99:10)
    at Object.createReadStream (fs.js:1706:10)
    at SendStream.stream (/snap/odrive/76/opt/OpenDrive/resources/app.asar/node_modules/send/index.js:797:19)
    at SendStream.send (/snap/odrive/76/opt/OpenDrive/resources/app.asar/node_modules/send/index.js:708:8)
    at onstat (/snap/odrive/76/opt/OpenDrive/resources/app.asar/node_modules/send/index.js:730:10)
    at process.nextTick (ELECTRON_ASAR.js:21:28)
    at process._tickCallback (internal/process/next_tick.js:61:11)
Error: ENOENT, public/javascript/settings.js not found in /snap/odrive/76/opt/OpenDrive/resources/app.asar
    at createError (ELECTRON_ASAR.js:131:17)
    at Object.module.(anonymous function) [as open] (ELECTRON_ASAR.js:195:23)
    at ReadStream.open (internal/fs/streams.js:110:12)
    at new ReadStream (internal/fs/streams.js:99:10)
    at Object.createReadStream (fs.js:1706:10)
    at SendStream.stream (/snap/odrive/76/opt/OpenDrive/resources/app.asar/node_modules/send/index.js:797:19)
    at SendStream.send (/snap/odrive/76/opt/OpenDrive/resources/app.asar/node_modules/send/index.js:708:8)
    at onstat (/snap/odrive/76/opt/OpenDrive/resources/app.asar/node_modules/send/index.js:730:10)
    at process.nextTick (ELECTRON_ASAR.js:21:28)
    at process._tickCallback (internal/process/next_tick.js:61:11)
``` 

**Desktop (please complete the following information):**
 - OS: Manjaro Linux (Gnome) 64 bit 18.1.2
- Odrive: Odrive 0.2.2 from Snapd --edge install
 
**Additional Information**
- Cannot use Odrive's App Image provided from GitHub in current OS.
- The operating system use a proxy for connection. I wonder if this issue comes from network connection failure.

**Comment by liberodark** [comment]
Please dont use snap version

**Comment by refee** [comment]
Thank you for your kind reply, currently I switched to another build of manjaro (gnome -> i3) therefore cannot provide further information in previous environment. I will test in i3 later and update this issue.

**Comment by liberodark** [comment]
Ok thank for your information
