### ISSUE TITLE
Mac build Error

### ISSUE THREAD

**Issue by liberodark** [liberodark/ODrive#29]
npm run release-mac

> odrive@0.1.3 release-mac /home/pc/Documents/Github/ODrive
> electron-builder --mac

  • electron-builder version=19.55.2
  • loaded configuration file=package.json ("build" field)
  • writing effective config file=dist/electron-builder.yaml
  • rebuilding native production dependencies platform=darwin arch=x64
  • packaging       platform=darwin arch=x64 electron=1.8.4 appOutDir=dist/mac
Downloading tmp-27142-0-electron-v1.8.4-darwin-x64.zip
[============================================>] 100.0% of 48.34 MB (1.37 MB/s)
  • skipped macOS application code signing reason=supported only on macOS
  • building        target=DMG arch=x64 file=dist/Open Drive-0.1.3.dmg
Error: spawn hdiutil ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:201:19)
    at onErrorNT (internal/child_process.js:379:16)
    at process._tickCallback (internal/process/next_tick.js:114:19)
From previous event:
    at spawn (/home/pc/Documents/Github/ODrive/node_modules/builder-util/src/util.ts:200:3)
    at /home/pc/Documents/Github/ODrive/node_modules/electron-builder-lib/src/targets/dmg.ts:229:9
    at Generator.next (<anonymous>)
From previous event:
    at createStageDmg (/home/pc/Documents/Github/ODrive/node_modules/electron-builder-lib/out/targets/dmg.js:25:21)
    at /home/pc/Documents/Github/ODrive/node_modules/electron-builder-lib/src/targets/dmg.ts:33:27
    at Generator.next (<anonymous>)
From previous event:
    at DmgTarget.build (/home/pc/Documents/Github/ODrive/node_modules/electron-builder-lib/out/targets/dmg.js:253:11)
    at taskManager.addTask.default.map.it (/home/pc/Documents/Github/ODrive/node_modules/electron-builder-lib/src/platformPackager.ts:120:67)
From previous event:
    at MacPackager.packageInDistributableFormat (/home/pc/Documents/Github/ODrive/node_modules/electron-builder-lib/src/platformPackager.ts:120:23)
    at /home/pc/Documents/Github/ODrive/node_modules/electron-builder-lib/src/macPackager.ts:92:26
    at runCallback (timers.js:763:18)
    at tryOnImmediate (timers.js:734:5)
    at processImmediate (timers.js:716:5)
From previous event:
    at /home/pc/Documents/Github/ODrive/node_modules/electron-builder-lib/src/macPackager.ts:92:10
    at Generator.next (<anonymous>)
From previous event:
    at MacPackager.pack (/home/pc/Documents/Github/ODrive/node_modules/electron-builder-lib/out/macPackager.js:200:11)
    at /home/pc/Documents/Github/ODrive/node_modules/electron-builder-lib/src/packager.ts:364:24
    at Generator.next (<anonymous>)
    at xfs.stat (/home/pc/Documents/Github/ODrive/node_modules/fs-extra-p/node_modules/fs-extra/lib/mkdirs/mkdirs.js:56:16)
    at /home/pc/Documents/Github/ODrive/node_modules/graceful-fs/polyfills.js:287:18
    at FSReqWrap.oncomplete (fs.js:171:5)
From previous event:
    at Packager.doBuild (/home/pc/Documents/Github/ODrive/node_modules/electron-builder-lib/out/packager.js:432:11)
    at /home/pc/Documents/Github/ODrive/node_modules/electron-builder-lib/src/packager.ts:308:52
    at Generator.next (<anonymous>)
    at /home/pc/Documents/Github/ODrive/node_modules/graceful-fs/graceful-fs.js:99:16
    at /home/pc/Documents/Github/ODrive/node_modules/graceful-fs/graceful-fs.js:43:10
    at FSReqWrap.oncomplete (fs.js:153:20)
From previous event:
    at Packager._build (/home/pc/Documents/Github/ODrive/node_modules/electron-builder-lib/out/packager.js:376:11)
    at /home/pc/Documents/Github/ODrive/node_modules/electron-builder-lib/src/packager.ts:270:23
    at Generator.next (<anonymous>)
    at runCallback (timers.js:763:18)
    at tryOnImmediate (timers.js:734:5)
    at processImmediate (timers.js:716:5)
From previous event:
    at Packager.build (/home/pc/Documents/Github/ODrive/node_modules/electron-builder-lib/out/packager.js:332:11)
    at /home/pc/Documents/Github/ODrive/node_modules/electron-builder/src/builder.ts:310:40
    at Generator.next (<anonymous>)
From previous event:
    at _build (/home/pc/Documents/Github/ODrive/node_modules/electron-builder/out/builder.js:61:21)
    at build (/home/pc/Documents/Github/ODrive/node_modules/electron-builder/src/builder.ts:280:10)
    at then (/home/pc/Documents/Github/ODrive/node_modules/electron-builder/src/cli/cli.ts:48:33)
    at runCallback (timers.js:763:18)
    at tryOnImmediate (timers.js:734:5)
    at processImmediate (timers.js:716:5)
From previous event:
    at Object.args [as handler] (/home/pc/Documents/Github/ODrive/node_modules/electron-builder/src/cli/cli.ts:48:33)
    at Object.runCommand (/home/pc/Documents/Github/ODrive/node_modules/electron-builder/node_modules/yargs/lib/command.js:235:44)
    at Object.parseArgs [as _parseArgs] (/home/pc/Documents/Github/ODrive/node_modules/electron-builder/node_modules/yargs/yargs.js:1041:24)
    at Object.get [as argv] (/home/pc/Documents/Github/ODrive/node_modules/electron-builder/node_modules/yargs/yargs.js:957:21)
    at Object.<anonymous> (/home/pc/Documents/Github/ODrive/node_modules/electron-builder/src/cli/cli.ts:42:15)
    at Module._compile (module.js:649:30)
    at Object.Module._extensions..js (module.js:660:10)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:501:12)
    at Function.Module._load (module.js:493:3)
    at Function.Module.runMain (module.js:690:10)
    at startup (bootstrap_node.js:194:16)
    at bootstrap_node.js:666:3

**Comment by liberodark** [comment]
Fixed need to compile on mac
