### ISSUE TITLE
Error when compiling

### ISSUE THREAD

**Issue by babasa** [liberodark/ODrive#35]
When try to run npm start i get this error

```
> odrive@0.2.0 start /root/ODrive
> electron main

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! odrive@0.2.0 start: `electron main`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the odrive@0.2.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-05-27T21_10_33_016Z-debug.log
```

and log /root/.npm/_logs/2018-05-27T21_10_33_016Z-debug.log have this 

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'start' ]
2 info using npm@5.6.0
3 info using node@v10.2.1
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle odrive@0.2.0~prestart: odrive@0.2.0
6 info lifecycle odrive@0.2.0~start: odrive@0.2.0
7 verbose lifecycle odrive@0.2.0~start: unsafe-perm in lifecycle true
8 verbose lifecycle odrive@0.2.0~start: PATH: /usr/local/lib/node_modules/npm/n$
9 verbose lifecycle odrive@0.2.0~start: CWD: /root/ODrive
10 silly lifecycle odrive@0.2.0~start: Args: [ '-c', 'electron main' ]
11 silly lifecycle odrive@0.2.0~start: Returned: code: 1  signal: null
12 info lifecycle odrive@0.2.0~start: Failed to exec start script
13 verbose stack Error: odrive@0.2.0 start: `electron main`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/n$
13 verbose stack     at EventEmitter.emit (events.js:182:13)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/n$
13 verbose stack     at ChildProcess.emit (events.js:182:13)
```
Can someone help me, thank you

**Comment by coyotte508** [comment]
Try this in the folder of the project:

```
sudo npm install -g electron # only once
electron main
```

Hopefully there will be more debug info shown.

**Comment by liberodark** [comment]
Did you succeed ?
