### ISSUE TITLE
Files list done! ends with ETIMEDOUT

### ISSUE THREAD

**Issue by mik13ST** [liberodark/ODrive#54]
> Files list done!
Files list done!
Files list done!
Files list done!
Files list done!
Files list done!
syncing false
Updated syncing status
Updating tray icon, connected:  true syncing:  false
{ Error: connect ETIMEDOUT 216.58.201.74:443
    at Object._errnoException (util.js:1024:11)
    at _exceptionWithHostPort (util.js:1046:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1182:14)
  code: 'ETIMEDOUT',
  errno: 'ETIMEDOUT',
  syscall: 'connect',
  address: '216.58.201.74',
  port: 443 }

My system is ArchLinux, kernel 4.19.8. I tried both the snap package `odrive-unofficial` and cloning repo and running `npm i` and then `npm start`. Both resulted in this error occurring after 5+ minutes of `Getting files info...`. I ran this app from terminal and this is the tail of the terminal log.

I have good knowledge of node.js and electron, I know how to debug node.js apps in Chrome Dev Tools, so I can provide any information to debug this.

I also tried to open drive.google.com in web browser while `Getting files info...` to somehow help with keeping the connection alive or something. It didn't help.

**Comment by liberodark** [comment]
Sorry is not official release you have try appimage ?

**Comment by liberodark** [comment]
For Arch Linux have official build
New build is coming

**Comment by diegobiavati** [comment]
I'm also having this problem, I use Manjaro with Deepin and appimage.

**Comment by liberodark** [comment]
ok now have push official release sudo snap install --edge odrive and 0.2.1
