### ISSUE TITLE
Syncronization stuck after deleting many files locally

### ISSUE THREAD

**Issue by wonx** [liberodark/ODrive#60]
I have a folder which stores videos and still images from a webcam, which are synced from another device. There are lots of them, around a few thousand. I decided to do some cleaning and deleted many old, redundant or duplicated images, so only 122 files remained in the local folder.

Now, ODrive seems to be stuck syncing these files. The locally deleted files are still existing in the google drive website, the ODrive icon in the taskbar swill shows the red "synchronizing", and the main ODrive interface shows "Already synchronized". Hitting the blue "Synchronize" button does nothing.

I'm using version 0.2.0 from the snap store as found here: https://snapcraft.io/odrive-unofficial on Ubuntu 18.04 LTS, under the Gnome desktop environment.

Running odrive from a terminal, I see it tries to process all those changes I made, and near the end, there's an error message that could be related to this problem: 

```
Emitting last important event for /home/user/Google Drive/capture folder/motion/2017-08-10_21:42:13-03.jpg unlink
{ Error: File not found: 1--lhVsSrJQo00_U3ILJgYu3souU2NTTD.
    at Request._callback (/snap/odrive-unofficial/2/resources/app.asar/node_modules/google-auth-library/lib/transporters.js:85:15)
    at Request.self.callback (/snap/odrive-unofficial/2/resources/app.asar/node_modules/request/request.js:185:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request.<anonymous> (/snap/odrive-unofficial/2/resources/app.asar/node_modules/request/request.js:1161:10)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at IncomingMessage.<anonymous> (/snap/odrive-unofficial/2/resources/app.asar/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:111:20)
  code: 404,
  errors: 
   [ { domain: 'global',
       reason: 'notFound',
       message: 'File not found: 1--lhVsSrJQo00_U3ILJgYu3souU2NTTD.',
       locationType: 'parameter',
       location: 'fileId' } ] }
local change false true
Unhandled rejection File not found: 1--lhVsSrJQo00_U3ILJgYu3souU2NTTD.
{ Error: File not found: 1--lhVsSrJQo00_U3ILJgYu3souU2NTTD.
    at Request._callback (/snap/odrive-unofficial/2/resources/app.asar/node_modules/google-auth-library/lib/transporters.js:85:15)
    at Request.self.callback (/snap/odrive-unofficial/2/resources/app.asar/node_modules/request/request.js:185:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request.<anonymous> (/snap/odrive-unofficial/2/resources/app.asar/node_modules/request/request.js:1161:10)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at IncomingMessage.<anonymous> (/snap/odrive-unofficial/2/resources/app.asar/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:111:20)
  code: 404,
  errors: 
   [ { domain: 'global',
       reason: 'notFound',
       message: 'File not found: 1--lhVsSrJQo00_U3ILJgYu3souU2NTTD.',
       locationType: 'parameter',
       location: 'fileId' } ] }
Events [ 'unlink' ]
```

This is only the error part. The whole output is much longer. Tell me if you want to see the whole thing.

**Comment by liberodark** [comment]
Ok please try to remove local db of odrive or test appimage.

Cordialy

**Comment by wonx** [comment]
I renamed the whole ~/.config/odrive directory, but the problem persist (exact same error as indicated above). Which leads me to think that odrive was not using that directory at all, since the configuration was not lost. 

I saw there was another odrive folder at ~/snap/odrive-unofficial/, but I can't find any configuration directory. I tried renaming the folder ~/snap/odrive-unofficial/common/.cache/ , but after recreating that dir, odrive showed the exact same error.

I would try the appimage version, but I see it's the same version as in the ubuntu repository.
What should I do next?

**Comment by wonx** [comment]
Update: I uninstalled the snap repository version and used the appimage provided in this github page. The sincronization seemed to progress until the UI showed this error: 

![captura de pantalla de 2019-01-31 18-28-10](https://user-images.githubusercontent.com/2736639/52092702-67460c00-2586-11e9-8178-876cd3d6db54.png)

This is what the console showed at that point. Note that the first of the two errors (ENOSPC) was repeated for every file, although they seemed to be successfully synced to my computer. the "rimraf" one only happened once and the synchronization halted: 

```
Events [ 'add' ]
Emitting last important event for /home/user/Google Drive/video captures/motion/2016-08-09_10:12:16-00.avi add
ignoring events for path /home/user/Google Drive/video captures/motion/2016-08-09_10:12:22-00.jpg
Watcher error: Error: watch /home/user/Google Drive/video captures/motion/2016-08-09_10:12:22-00.jpg ENOSPC
Downloaded 2016-08-09_10:12:22-00.jpg!
Downloading  { id: '1Ej0gvKwJhdOnDWZ7Q9eBmjcn3gdJpHfL',
  name: '2016-08-09_10:12:21-00.jpg',
  mimeType: 'image/jpeg',
  trashed: false,
  parents: [ '1_ctl9CX6hOxzUJ_WYixDij09Tpl7siYE' ],
  modifiedTime: '2016-08-09T08:12:22.173Z',
  md5Checksum: '64f71fbb1d7fd0d33873db5559be5926',
  size: '29356' }
Events [ 'add' ]
Emitting last important event for /home/user/Google Drive/video captures/motion/2016-08-09_10:12:22-00.jpg add
ignoring events for path /home/user/Google Drive/video captures/motion/2016-08-09_10:12:21-00.jpg
{ Error: socket hang up
    at TLSSocket.onHangUp (_tls_wrap.js:1130:19)
    at Object.onceWrapper (events.js:314:30)
    at emitNone (events.js:110:20)
    at TLSSocket.emit (events.js:207:7)
    at endReadableNT (_stream_readable.js:1045:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
  code: 'ECONNRESET',
  path: null,
  host: 'www.googleapis.com',
  port: 443,
  localAddress: undefined }
syncing false
Updated syncing status
Updating tray icon, connected:  true syncing:  false
{ AssertionError [ERR_ASSERTION]: rimraf: path should be a string
    at Object.rimraf (/tmp/.mount_odriveQWp83Q/app/resources/app.asar/node_modules/fs-extra/lib/remove/rimraf.js:36:10)
    at Promise (/tmp/.mount_odriveQWp83Q/app/resources/app.asar/node_modules/universalify/index.js:13:12)
    at Promise (<anonymous>)
    at Object.rimraf [as remove] (/tmp/.mount_odriveQWp83Q/app/resources/app.asar/node_modules/universalify/index.js:7:14)
    at Promise.catch (/tmp/.mount_odriveQWp83Q/app/resources/app.asar/app/core/sync.js:965:18)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
  generatedMessage: false,
  name: 'AssertionError [ERR_ASSERTION]',
  code: 'ERR_ASSERTION',
  actual: 'object',
  expected: 'string',
  operator: '==' }
```

**Comment by liberodark** [comment]
ok now have push official release sudo snap install --edge odrive

**Comment by wonx** [comment]
Ok, I don't know what I am doing wrong, but I installed the snap version that you just pushed, and I get a bunch of "Permission denied" messages, like 

> shm_open() failed: Permission denied

 right at the start, and a bunch of these: 

```
Error when watching changes...
remote change false false
Updated syncing status
Updating tray icon, connected:  true syncing:  false
Unhandled rejection EACCES: permission denied, open '/home/user/Google Drive/Others/PROJECT.doc.docx'
{ [Error: EACCES: permission denied, open '/home/user/Google Drive/Others/PROJECT.doc.docx']
  errno: -13,
  code: 'EACCES',
  syscall: 'open',
  path:
   '/home/user/Google Drive/Others/PROJECT.doc.docx',
  watcher: true }

```

Looks like a permission problem, but I already made sure the snap application has access to my home folder.
Also, creating a new folder or file in my local gdrive foldre is not being synchronized to google drive.

**Comment by liberodark** [comment]
Please try 0.2.2 deb is work ?

**Comment by chihwahli** [comment]
Bump: problem persist. Clean install Ubuntu version 18.04.2. Same error as threat poster. How can I try 0.2.2 deb ? Please tell me.
