### ISSUE TITLE
Fedora Crash / Icon Tray no visible

### ISSUE THREAD

**Issue by h-g-s** [liberodark/ODrive#67]
Hi, I'm built the version from git master and started the first synchronization in Fedora 29. After some time with messages "Files list done!"  I got the following error:
..
Files list done!
syncing false
Updated syncing status
Updating tray icon, connected:  true syncing:  false
{ Error: Internal Error
    at Request._callback (/home/haroldo/src/ODrive/node_modules/google-auth-library/lib/transporters.js:85:15)
    at Request.self.callback (/home/haroldo/src/ODrive/node_modules/request/request.js:185:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request.<anonymous> (/home/haroldo/src/ODrive/node_modules/request/request.js:1161:10)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at IncomingMessage.<anonymous> (/home/haroldo/src/ODrive/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:111:20)
  code: 500,
  errors: 
   [ { domain: 'global',
       reason: 'internalError',
       message: 'Internal Error' } ] }

**Comment by liberodark** [comment]
ok try the 0.2.1 version.

**Comment by liberodark** [comment]
now have push official release sudo snap install --edge odrive

**Comment by h-g-s** [comment]
Thanks for answering, I installed with 
snap install --edge odriv
and executed now with snap run odrive,   but after some time the following error was reported:
Watching remote changes...
remote change true true
Updated syncing status
Updating tray icon, connected:  true syncing:  true
Error when watching changes...
remote change false false
Updated syncing status
Updating tray icon, connected:  true syncing:  false
Unhandled rejection Error processing argument at index 0, conversion failure from /snap/odrive/5/opt/OpenDrive/resources/app.asar/public/images/logo.png
TypeError: Error processing argument at index 0, conversion failure from /snap/odrive/5/opt/OpenDrive/resources/app.asar/public/images/logo.png
    at updateTrayIcon (/snap/odrive/5/opt/OpenDrive/resources/app.asar/main.js:127:12)
    at Globals.gbs.on (/snap/odrive/5/opt/OpenDrive/resources/app.asar/main.js:120:5)
    at Globals.emit (events.js:182:13)
    at Globals.updateSyncing (/snap/odrive/5/opt/OpenDrive/resources/app.asar/config/globals.js:35:10)
    at Sync.syncObject.on.syncing (/snap/odrive/5/opt/OpenDrive/resources/app.asar/app/core/account.js:144:49)
    at Sync.emit (events.js:182:13)
    at Sync.set handlingRemoteChange [as handlingRemoteChange] (/snap/odrive/5/opt/OpenDrive/resources/app.asar/app/core/sync.js:67:10)
    at Sync.watchChanges (/snap/odrive/5/opt/OpenDrive/resources/app.asar/app/core/sync.js:234:33)
    at process._tickCallback (internal/process/next_tick.js:68:7)

**Comment by liberodark** [comment]
yeah snap is hard with strict use have make update better do not use snap !

**Comment by h-g-s** [comment]
Runing without snap (installed in /opt/ODrive), in another machine with Fedora 29 I got the following assertion Failure:
{ AssertionError [ERR_ASSERTION]: rimraf: path should be a string
    at Object.rimraf (/opt/ODrive/resources/app.asar/node_modules/fs-extra/lib/remove/rimraf.js:36:10)
    at Promise (/opt/ODrive/resources/app.asar/node_modules/universalify/index.js:13:12)
    at new Promise (<anonymous>)
    at Object.rimraf [as remove] (/opt/ODrive/resources/app.asar/node_modules/universalify/index.js:7:14)
    at Promise.catch (/opt/ODrive/resources/app.asar/app/core/sync.js:965:18)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
  generatedMessage: false,
  name: 'AssertionError [ERR_ASSERTION]',
  code: 'ERR_ASSERTION',
  actual: 'object',
  expected: 'string',
  operator: '===' }

**Comment by liberodark** [comment]
Is strange on try to look on Fedora 29

**Comment by liberodark** [comment]
Ok have test working great on fedora : 

<a href="https://i.imgur.com/9PNZ5ha.png">
  <img src="https://imgur.com/9PNZ5hal.png" />
</a>

But not see app icon on the bar :( but is runing background

**Comment by h-g-s** [comment]
Is there any other information that I can give you to indicate why it my synchronization is crashing ?

**Comment by liberodark** [comment]
im try to fix icon now

**Comment by liberodark** [comment]
you have try appimage ?

**Comment by liberodark** [comment]
for fedora have found : libXss.so.1 missing

**Comment by h-g-s** [comment]
I have libXss.so.1 installed on my system.

**Comment by liberodark** [comment]
Have try again on fedora with the beta version is same is work 

<a href="https://i.imgur.com/4IcDjPp.png">
  <img src="https://imgur.com/4IcDjPpl.png" />
</a>

**Comment by liberodark** [comment]
Please make test from source !

**Comment by h-g-s** [comment]
npm test seem that is passing:
haroldo ~/src/ODrive $  npm test
> odrive@0.2.2 test /home/haroldo/src/ODrive
> npm run lint


> odrive@0.2.2 lint /home/haroldo/src/ODrive
> eslint app main.js

**Comment by h-g-s** [comment]
Running now from the source diretory (npm start), with the last version, I got:

 'change',
  'change',
  'change' ]
Emitting last event for /home/haroldo/Google Drive/Google Fotos/20180407_143351.jpg
ignoring events for path /home/haroldo/Google Drive/Google Fotos/20180407_143349.jpg
{ Error: getaddrinfo ENOTFOUND www.googleapis.com www.googleapis.com:443
    at errnoException (dns.js:50:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:92:26)
  code: 'ENOTFOUND',
  errno: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 'www.googleapis.com',
  host: 'www.googleapis.com',
  port: 443 }
syncing false
Updated syncing status
Updating tray icon, connected:  true syncing:  false
{ AssertionError [ERR_ASSERTION]: rimraf: path should be a string
    at Object.rimraf (/home/haroldo/src/ODrive/node_modules/fs-extra/lib/remove/rimraf.js:36:10)
    at Promise (/home/haroldo/src/ODrive/node_modules/universalify/index.js:13:12)
    at new Promise (<anonymous>)
    at Object.rimraf [as remove] (/home/haroldo/src/ODrive/node_modules/universalify/index.js:7:14)
    at Promise.catch (/home/haroldo/src/ODrive/app/core/sync.js:965:18)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
  generatedMessage: false,
  name: 'AssertionError [ERR_ASSERTION]',
  code: 'ERR_ASSERTION',
  actual: 'object',
  expected: 'string',
  operator: '===' }

**Comment by liberodark** [comment]
ok thank you for this test

**Comment by liberodark** [comment]
https://www78.uptobox.com/dl/mO71Zrii1iwONnBptilsiaUfNZALA1AeeTD-vhXo2r3fmFqUiddQl6oKpqx9HZ_g2UNIRXlHogN9oGwBJRg9BekqcUyrpnIvv9xYWqKQz1ParO75uExuWtgnDw7wDcHgfK-7d-ZucUlF61lZwSFAmg/OpenDrive%200.2.2.AppImage

**Comment by liberodark** [comment]
Have try in wayland or xorg is same no icon have just this bug

**Comment by liberodark** [comment]
Have find solution by Leeo : 
Need to install 
https://extensions.gnome.org/extension/615/appindicator-support/
sudo yum install libappindicator-gtk3
[![https://imgur.com/x4zteWM.png](https://imgur.com/x4zteWM.png)](https://imgur.com/x4zteWM.png)
